### ISSUE TITLE
restlib package - goimports issue

### ISSUE THREAD

**Issue by pgmitche** [anz-bank/syslgen-examples#5]
@kasunfdo package restlib defined in `lib` directory.

Generated code references `restlib` but does not alias lib directory to `restlib`. Import removed by gofmt/goimports if no alias is defined as package should align with parent directory name.

Code that then uses restlib in dot notation then fails to find dependency.

Action: Rename `lib` directory to `restlib`

**Comment by kasunfdo** [comment]
Renamed dir `lib` to `restlib`
